App\Entities\User:
  type: entity
  table: users

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
    email:
      type: string
    password:
      type: string